[workspace]

members = [
    "abusiveexperiencereport/v1/lib",
    "abusiveexperiencereport/v1/cli",
    "acceleratedmobilepageurl/v1/lib",
    "acceleratedmobilepageurl/v1/cli",
    "accessapproval/v1/lib",
    "accessapproval/v1/cli",
    "accesscontextmanager/v1beta/lib",
    "accesscontextmanager/v1beta/cli",
    "accesscontextmanager/v1/lib",
    "accesscontextmanager/v1/cli",
    "adexchangebuyer/v1.2/lib",
    "adexchangebuyer/v1.2/cli",
    "adexchangebuyer/v1.3/lib",
    "adexchangebuyer/v1.3/cli",
    "adexchangebuyer/v1.4/lib",
    "adexchangebuyer/v1.4/cli",
    "adexchangebuyer/v2beta1/lib",
    "adexchangebuyer/v2beta1/cli",
    "adexperiencereport/v1/lib",
    "adexperiencereport/v1/cli",
    "admin/datatransfer_v1/lib",
    "admin/datatransfer_v1/cli",
    "admin/directory_v1/lib",
    "admin/directory_v1/cli",
    "admin/reports_v1/lib",
    "admin/reports_v1/cli",
    "admob/v1/lib",
    "admob/v1/cli",
    "adsense/v1.4/lib",
    "adsense/v1.4/cli",
    "adsensehost/v4.1/lib",
    "adsensehost/v4.1/cli",
    "alertcenter/v1beta1/lib",
    "alertcenter/v1beta1/cli",
    "analytics/v3/lib",
    "analytics/v3/cli",
    "analyticsreporting/v4/lib",
    "analyticsreporting/v4/cli",
    "androiddeviceprovisioning/v1/lib",
    "androiddeviceprovisioning/v1/cli",
    "androidenterprise/v1/lib",
    "androidenterprise/v1/cli",
    "androidmanagement/v1/lib",
    "androidmanagement/v1/cli",
    "androidpublisher/v3/lib",
    "androidpublisher/v3/cli",
    "apigee/v1/lib",
    "apigee/v1/cli",
    "appengine/v1alpha/lib",
    "appengine/v1alpha/cli",
    "appengine/v1beta/lib",
    "appengine/v1beta/cli",
    "appengine/v1/lib",
    "appengine/v1/cli",
    "bigquery/v2/lib",
    "bigquery/v2/cli",
    "bigqueryconnection/v1beta1/lib",
    "bigqueryconnection/v1beta1/cli",
    "bigquerydatatransfer/v1/lib",
    "bigquerydatatransfer/v1/cli",
    "bigqueryreservation/v1beta1/lib",
    "bigqueryreservation/v1beta1/cli",
    "bigqueryreservation/v1/lib",
    "bigqueryreservation/v1/cli",
    "bigtableadmin/v1/lib",
    "bigtableadmin/v1/cli",
    "bigtableadmin/v2/lib",
    "bigtableadmin/v2/cli",
    "billingbudgets/v1beta1/lib",
    "billingbudgets/v1beta1/cli",
    "binaryauthorization/v1beta1/lib",
    "binaryauthorization/v1beta1/cli",
    "binaryauthorization/v1/lib",
    "binaryauthorization/v1/cli",
    "blogger/v2/lib",
    "blogger/v2/cli",
    "blogger/v3/lib",
    "blogger/v3/cli",
    "books/v1/lib",
    "books/v1/cli",
    "calendar/v3/lib",
    "calendar/v3/cli",
    "chat/v1/lib",
    "chat/v1/cli",
    "civicinfo/v2/lib",
    "civicinfo/v2/cli",
    "classroom/v1/lib",
    "classroom/v1/cli",
    "cloudasset/v1p1beta1/lib",
    "cloudasset/v1p1beta1/cli",
    "cloudasset/v1p4beta1/lib",
    "cloudasset/v1p4beta1/cli",
    "cloudasset/v1beta1/lib",
    "cloudasset/v1beta1/cli",
    "cloudasset/v1/lib",
    "cloudasset/v1/cli",
    "cloudbilling/v1/lib",
    "cloudbilling/v1/cli",
    "cloudbuild/v1alpha1/lib",
    "cloudbuild/v1alpha1/cli",
    "cloudbuild/v1alpha2/lib",
    "cloudbuild/v1alpha2/cli",
    "cloudbuild/v1/lib",
    "cloudbuild/v1/cli",
    "clouddebugger/v2/lib",
    "clouddebugger/v2/cli",
    "clouderrorreporting/v1beta1/lib",
    "clouderrorreporting/v1beta1/cli",
    "cloudfunctions/v1/lib",
    "cloudfunctions/v1/cli",
    "cloudidentity/v1beta1/lib",
    "cloudidentity/v1beta1/cli",
    "cloudidentity/v1/lib",
    "cloudidentity/v1/cli",
    "cloudiot/v1/lib",
    "cloudiot/v1/cli",
    "cloudkms/v1/lib",
    "cloudkms/v1/cli",
    "cloudprofiler/v2/lib",
    "cloudprofiler/v2/cli",
    "cloudresourcemanager/v1beta1/lib",
    "cloudresourcemanager/v1beta1/cli",
    "cloudresourcemanager/v2beta1/lib",
    "cloudresourcemanager/v2beta1/cli",
    "cloudresourcemanager/v1/lib",
    "cloudresourcemanager/v1/cli",
    "cloudresourcemanager/v2/lib",
    "cloudresourcemanager/v2/cli",
    "cloudscheduler/v1beta1/lib",
    "cloudscheduler/v1beta1/cli",
    "cloudscheduler/v1/lib",
    "cloudscheduler/v1/cli",
    "cloudsearch/v1/lib",
    "cloudsearch/v1/cli",
    "cloudshell/v1alpha1/lib",
    "cloudshell/v1alpha1/cli",
    "cloudshell/v1/lib",
    "cloudshell/v1/cli",
    "cloudtasks/v2beta2/lib",
    "cloudtasks/v2beta2/cli",
    "cloudtasks/v2beta3/lib",
    "cloudtasks/v2beta3/cli",
    "cloudtasks/v2/lib",
    "cloudtasks/v2/cli",
    "cloudtrace/v2beta1/lib",
    "cloudtrace/v2beta1/cli",
    "cloudtrace/v1/lib",
    "cloudtrace/v1/cli",
    "cloudtrace/v2/lib",
    "cloudtrace/v2/cli",
    "composer/v1beta1/lib",
    "composer/v1beta1/cli",
    "composer/v1/lib",
    "composer/v1/cli",
    "compute/alpha/lib",
    "compute/alpha/cli",
    "compute/beta/lib",
    "compute/beta/cli",
    "compute/v1/lib",
    "compute/v1/cli",
    "container/v1beta1/lib",
    "container/v1beta1/cli",
    "container/v1/lib",
    "container/v1/cli",
    "containeranalysis/v1alpha1/lib",
    "containeranalysis/v1alpha1/cli",
    "containeranalysis/v1beta1/lib",
    "containeranalysis/v1beta1/cli",
    "content/v2/lib",
    "content/v2/cli",
    "content/v2.1/lib",
    "content/v2.1/cli",
    "customsearch/v1/lib",
    "customsearch/v1/cli",
    "datacatalog/v1beta1/lib",
    "datacatalog/v1beta1/cli",
    "dataflow/v1b3/lib",
    "dataflow/v1b3/cli",
    "datafusion/v1beta1/lib",
    "datafusion/v1beta1/cli",
    "dataproc/v1beta2/lib",
    "dataproc/v1beta2/cli",
    "dataproc/v1/lib",
    "dataproc/v1/cli",
    "datastore/v1beta1/lib",
    "datastore/v1beta1/cli",
    "datastore/v1beta3/lib",
    "datastore/v1beta3/cli",
    "datastore/v1/lib",
    "datastore/v1/cli",
    "deploymentmanager/alpha/lib",
    "deploymentmanager/alpha/cli",
    "deploymentmanager/v2beta/lib",
    "deploymentmanager/v2beta/cli",
    "deploymentmanager/v2/lib",
    "deploymentmanager/v2/cli",
    "dfareporting/v3.3/lib",
    "dfareporting/v3.3/cli",
    "dfareporting/v3.4/lib",
    "dfareporting/v3.4/cli",
    "dialogflow/v2beta1/lib",
    "dialogflow/v2beta1/cli",
    "dialogflow/v2/lib",
    "dialogflow/v2/cli",
    "digitalassetlinks/v1/lib",
    "digitalassetlinks/v1/cli",
    "discovery/v1/lib",
    "discovery/v1/cli",
    "displayvideo/v1/lib",
    "displayvideo/v1/cli",
    "dlp/v2/lib",
    "dlp/v2/cli",
    "dns/v1beta2/lib",
    "dns/v1beta2/cli",
    "dns/v1/lib",
    "dns/v1/cli",
    "docs/v1/lib",
    "docs/v1/cli",
    "domainsrdap/v1/lib",
    "domainsrdap/v1/cli",
    "doubleclickbidmanager/v1/lib",
    "doubleclickbidmanager/v1/cli",
    "doubleclicksearch/v2/lib",
    "doubleclicksearch/v2/cli",
    "drive/v2/lib",
    "drive/v2/cli",
    "drive/v3/lib",
    "drive/v3/cli",
    "driveactivity/v2/lib",
    "driveactivity/v2/cli",
    "factchecktools/v1alpha1/lib",
    "factchecktools/v1alpha1/cli",
    "fcm/v1/lib",
    "fcm/v1/cli",
    "file/v1beta1/lib",
    "file/v1beta1/cli",
    "file/v1/lib",
    "file/v1/cli",
    "firebase/v1beta1/lib",
    "firebase/v1beta1/cli",
    "firebasedynamiclinks/v1/lib",
    "firebasedynamiclinks/v1/cli",
    "firebasehosting/v1beta1/lib",
    "firebasehosting/v1beta1/cli",
    "firebaseml/v1beta2/lib",
    "firebaseml/v1beta2/cli",
    "firebaserules/v1/lib",
    "firebaserules/v1/cli",
    "firestore/v1beta1/lib",
    "firestore/v1beta1/cli",
    "firestore/v1beta2/lib",
    "firestore/v1beta2/cli",
    "firestore/v1/lib",
    "firestore/v1/cli",
    "fitness/v1/lib",
    "fitness/v1/cli",
    "games/v1/lib",
    "games/v1/cli",
    "gamesConfiguration/v1configuration/lib",
    "gamesConfiguration/v1configuration/cli",
    "gamesManagement/v1management/lib",
    "gamesManagement/v1management/cli",
    "gameservices/v1beta/lib",
    "gameservices/v1beta/cli",
    "genomics/v1alpha2/lib",
    "genomics/v1alpha2/cli",
    "genomics/v2alpha1/lib",
    "genomics/v2alpha1/cli",
    "genomics/v1/lib",
    "genomics/v1/cli",
    "gmail/v1/lib",
    "gmail/v1/cli",
    "groupsmigration/v1/lib",
    "groupsmigration/v1/cli",
    "groupssettings/v1/lib",
    "groupssettings/v1/cli",
    "healthcare/v1beta1/lib",
    "healthcare/v1beta1/cli",
    "healthcare/v1/lib",
    "healthcare/v1/cli",
    "homegraph/v1/lib",
    "homegraph/v1/cli",
    "iam/v1/lib",
    "iam/v1/cli",
    "iamcredentials/v1/lib",
    "iamcredentials/v1/cli",
    "iap/v1beta1/lib",
    "iap/v1beta1/cli",
    "iap/v1/lib",
    "iap/v1/cli",
    "identitytoolkit/v3/lib",
    "identitytoolkit/v3/cli",
    "indexing/v3/lib",
    "indexing/v3/cli",
    "jobs/v3p1beta1/lib",
    "jobs/v3p1beta1/cli",
    "jobs/v3/lib",
    "jobs/v3/cli",
    "kgsearch/v1/lib",
    "kgsearch/v1/cli",
    "language/v1beta1/lib",
    "language/v1beta1/cli",
    "language/v1beta2/lib",
    "language/v1beta2/cli",
    "language/v1/lib",
    "language/v1/cli",
    "libraryagent/v1/lib",
    "libraryagent/v1/cli",
    "licensing/v1/lib",
    "licensing/v1/cli",
    "lifesciences/v2beta/lib",
    "lifesciences/v2beta/cli",
    "logging/v2/lib",
    "logging/v2/cli",
    "managedidentities/v1alpha1/lib",
    "managedidentities/v1alpha1/cli",
    "managedidentities/v1beta1/lib",
    "managedidentities/v1beta1/cli",
    "managedidentities/v1/lib",
    "managedidentities/v1/cli",
    "manufacturers/v1/lib",
    "manufacturers/v1/cli",
    "memcache/v1beta2/lib",
    "memcache/v1beta2/cli",
    "ml/v1/lib",
    "ml/v1/cli",
    "monitoring/v1/lib",
    "monitoring/v1/cli",
    "monitoring/v3/lib",
    "monitoring/v3/cli",
    "networkmanagement/v1beta1/lib",
    "networkmanagement/v1beta1/cli",
    "oauth/v2/lib",
    "oauth/v2/cli",
    "osconfig/v1/lib",
    "osconfig/v1/cli",
    "oslogin/v1alpha/lib",
    "oslogin/v1alpha/cli",
    "oslogin/v1beta/lib",
    "oslogin/v1beta/cli",
    "oslogin/v1/lib",
    "oslogin/v1/cli",
    "pagespeedonline/v5/lib",
    "pagespeedonline/v5/cli",
    "people/v1/lib",
    "people/v1/cli",
    "playcustomapp/v1/lib",
    "playcustomapp/v1/cli",
    "policytroubleshooter/v1beta/lib",
    "policytroubleshooter/v1beta/cli",
    "policytroubleshooter/v1/lib",
    "policytroubleshooter/v1/cli",
    "poly/v1/lib",
    "poly/v1/cli",
    "prod_tt_sasportal/v1alpha1/lib",
    "prod_tt_sasportal/v1alpha1/cli",
    "pubsub/v1beta1a/lib",
    "pubsub/v1beta1a/cli",
    "pubsub/v1beta2/lib",
    "pubsub/v1beta2/cli",
    "pubsub/v1/lib",
    "pubsub/v1/cli",
    "recommender/v1beta1/lib",
    "recommender/v1beta1/cli",
    "redis/v1beta1/lib",
    "redis/v1beta1/cli",
    "redis/v1/lib",
    "redis/v1/cli",
    "remotebuildexecution/v1alpha/lib",
    "remotebuildexecution/v1alpha/cli",
    "remotebuildexecution/v1/lib",
    "remotebuildexecution/v1/cli",
    "remotebuildexecution/v2/lib",
    "remotebuildexecution/v2/cli",
    "reseller/v1/lib",
    "reseller/v1/cli",
    "run/v1alpha1/lib",
    "run/v1alpha1/cli",
    "run/v1beta1/lib",
    "run/v1beta1/cli",
    "run/v1/lib",
    "run/v1/cli",
    "runtimeconfig/v1beta1/lib",
    "runtimeconfig/v1beta1/cli",
    "runtimeconfig/v1/lib",
    "runtimeconfig/v1/cli",
    "safebrowsing/v4/lib",
    "safebrowsing/v4/cli",
    "sasportal/v1alpha1/lib",
    "sasportal/v1alpha1/cli",
    "script/v1/lib",
    "script/v1/cli",
    "searchconsole/v1/lib",
    "searchconsole/v1/cli",
    "secretmanager/v1beta1/lib",
    "secretmanager/v1beta1/cli",
    "secretmanager/v1/lib",
    "secretmanager/v1/cli",
    "securitycenter/v1beta1/lib",
    "securitycenter/v1beta1/cli",
    "securitycenter/v1/lib",
    "securitycenter/v1/cli",
    "serviceconsumermanagement/v1/lib",
    "serviceconsumermanagement/v1/cli",
    "servicecontrol/v1/lib",
    "servicecontrol/v1/cli",
    "servicedirectory/v1beta1/lib",
    "servicedirectory/v1beta1/cli",
    "servicemanagement/v1/lib",
    "servicemanagement/v1/cli",
    "servicenetworking/v1beta/lib",
    "servicenetworking/v1beta/cli",
    "servicenetworking/v1/lib",
    "servicenetworking/v1/cli",
    "serviceusage/v1beta1/lib",
    "serviceusage/v1beta1/cli",
    "serviceusage/v1/lib",
    "serviceusage/v1/cli",
    "sheets/v4/lib",
    "sheets/v4/cli",
    "siteVerification/v1/lib",
    "siteVerification/v1/cli",
    "slides/v1/lib",
    "slides/v1/cli",
    "sourcerepo/v1/lib",
    "sourcerepo/v1/cli",
    "spanner/v1/lib",
    "spanner/v1/cli",
    "speech/v1p1beta1/lib",
    "speech/v1p1beta1/cli",
    "speech/v2beta1/lib",
    "speech/v2beta1/cli",
    "speech/v1/lib",
    "speech/v1/cli",
    "sqladmin/v1beta4/lib",
    "sqladmin/v1beta4/cli",
    "storage/v1/lib",
    "storage/v1/cli",
    "storagetransfer/v1/lib",
    "storagetransfer/v1/cli",
    "streetviewpublish/v1/lib",
    "streetviewpublish/v1/cli",
    "tagmanager/v1/lib",
    "tagmanager/v1/cli",
    "tagmanager/v2/lib",
    "tagmanager/v2/cli",
    "tasks/v1/lib",
    "tasks/v1/cli",
    "testing/v1/lib",
    "testing/v1/cli",
    "texttospeech/v1beta1/lib",
    "texttospeech/v1beta1/cli",
    "texttospeech/v1/lib",
    "texttospeech/v1/cli",
    "toolresults/v1beta3/lib",
    "toolresults/v1beta3/cli",
    "tpu/v1alpha1/lib",
    "tpu/v1alpha1/cli",
    "tpu/v1/lib",
    "tpu/v1/cli",
    "translate/v3beta1/lib",
    "translate/v3beta1/cli",
    "translate/v2/lib",
    "translate/v2/cli",
    "translate/v3/lib",
    "translate/v3/cli",
    "vault/v1/lib",
    "vault/v1/cli",
    "verifiedaccess/v1/lib",
    "verifiedaccess/v1/cli",
    "videointelligence/v1p1beta1/lib",
    "videointelligence/v1p1beta1/cli",
    "videointelligence/v1p2beta1/lib",
    "videointelligence/v1p2beta1/cli",
    "videointelligence/v1p3beta1/lib",
    "videointelligence/v1p3beta1/cli",
    "videointelligence/v1beta2/lib",
    "videointelligence/v1beta2/cli",
    "videointelligence/v1/lib",
    "videointelligence/v1/cli",
    "vision/v1p1beta1/lib",
    "vision/v1p1beta1/cli",
    "vision/v1p2beta1/lib",
    "vision/v1p2beta1/cli",
    "vision/v1/lib",
    "vision/v1/cli",
    "webfonts/v1/lib",
    "webfonts/v1/cli",
    "webmasters/v3/lib",
    "webmasters/v3/cli",
    "websecurityscanner/v1alpha/lib",
    "websecurityscanner/v1alpha/cli",
    "websecurityscanner/v1beta/lib",
    "websecurityscanner/v1beta/cli",
    "websecurityscanner/v1/lib",
    "websecurityscanner/v1/cli",
    "youtube/v3/lib",
    "youtube/v3/cli",
    "youtubeAnalytics/v2/lib",
    "youtubeAnalytics/v2/cli",
    "youtubereporting/v1/lib",
    "youtubereporting/v1/cli",
]
